### ISSUE TITLE
Support asynchronous server

### ISSUE THREAD

**Issue by jovany-wang** [baidu/starlight#131]

**Comment by jovany-wang** [comment]
I'd like to support this feature.

**Comment by wenweihu86** [comment]
@jovany-wang This is a very useful feature.

**Comment by jovany-wang** [comment]
OK, I'll finish it in the next several weeks.

**Comment by jovany-wang** [comment]
@wenweihu86 
I'd like to use `CompletableFuture` to support async server with its client. If this sounds good to you, I will send a simple document on this design. 

Please let me know your thoughts, thanks.

**Comment by FoghostCn** [comment]
The simplest scenario can be considered as rpc proxy. Asynchronous may effectively improve throughput. `CompletableFuture` may be a good choice. I think the asynchronous implementation in the client can also use `CompleteFuture` instead of callback, thanks

**Comment by jovany-wang** [comment]
@FoghostCn  
Maybe it's better to support both of the callback client and `CompletableFuture` client.

Another issue is that we should upgrade the JDK version to 1.8+.

**Comment by chen-xl-dev** [comment]
Expect asynchrony on the server side. If the server has network operation, asynchronous server can bring more performance improvement. Take a look at joyrpc.
