### ISSUE TITLE
java client 是否支持流式数据传输

### ISSUE THREAD

**Issue by Honei** [baidu/starlight#166]
我是 brpc 开发了 server 端，然后映射成了 restful 接口。但是最近传输大数据时，会出现超时问题。现在想转换为流式数据传输。server 端是 C++，请问 java 端的 client 是否支持流式数据传输。

**Comment by wenweihu86** [comment]
目前不支持

**Comment by WingsGo** [comment]
@wenweihu86 这个功能有计划支持么，或者可以提供下思路该如何实现么
