### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by lvjg** [baidu/starlight#168]
brpc-java在处理100KB以上http请求，在压力大情况下会有OOM的情况，导致服务不可用。
验证方式：发送100KB以上http body，极限压力下，堆外内存会持续上涨。

**Comment by raptium** [comment]
如果只是 HTTP 协议，那么 #162 重复了。
其它协议的你可以复现吗？

**Comment by lvjg** [comment]
BAIDU_STD也会
