### ISSUE TITLE
With the brpc processing, CPU cost will growth？

### ISSUE THREAD

**Issue by Zack-Ku** [baidu/starlight#186]
After my  program run for days , I find cpu cost much than beginning, and must restart the program.
I use arthas find out when channel is inactive , brpc will clean the FastFutureStroe ,that cost 600ms avg  .At the begging just cost few ms.
![image](https://user-images.githubusercontent.com/19411268/88775487-57c57480-d1b7-11ea-8215-d77568c782af.png)
I check the code ,find maybe the slot id growth lead to it. When clean futArray, it may run mili times for one process. 
![image](https://user-images.githubusercontent.com/19411268/88776507-a0c9f880-d1b8-11ea-9023-bec79a2b835e.png)
![image](https://user-images.githubusercontent.com/19411268/88776543-ad4e5100-d1b8-11ea-8fc6-d21cd05dc438.png)
Is there a solution for it? Or Am I have something wrong using brpc? 

Info:
     Java: 1.8
     QPS:  10k+

**Comment by sixbyter** [comment]
we have same problem.

**Comment by raptium** [comment]
@wenweihu86 Could you please take a look into this issue? I am not familiar with the `FastFutureStore`.

**Comment by h-zh-cn** [comment]
Will it be fixed soon ???
