### ISSUE TITLE
can increase the network usage for reading data from cpp server by java client

### ISSUE THREAD

**Issue by fzhedu** [baidu/starlight#363]
**Describe the bug**
https://github.com/apache/brpc/issues/2369

the brpc java client can read data from cpp server, but just using 30% network, so I wonder starlight can increase the network usage for such cases?

**To Reproduce**
2. See error

**Expected behavior**

**Additional context**

**Comment by tullyliu** [comment]
这块没有特别的设计，我理解是starlight是可以用满网络带宽的，不过可能在StarRocks的场景还需要streaming的能力，我们目前还没支持。

**Comment by fzhedu** [comment]
@tullyliu 明白，谢谢您的回复。
